### ISSUE TITLE
[PE-D][Tester C] UG lacks screenshots for examples

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-W14-2/tp#289]
Perhaps you could consider adding screenshots for each command to allow the user to better expect what each command should return. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Samsation/ped#5

**Comment by Hikoya** [comment]
Thank you for the suggestion. However, we would try not to put too many screenshots to avoid cluttering the user guide.
