### ISSUE TITLE
[PE-D][Tester C] Integration between stalls and reviews is not the most intuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-W14-2/tp#293]
As a user wanting to make use of FoodWhere (FW) to manage food reviews, the GUI can get really cluttered really quickly, especially when there is multiple reviews for a single stall. Furthermore, with almost 2 of each typology of commands, 1 for each list, it can get quite confusing for the user.

Perhaps you could consider just having the stalls as the main display, then for each review added to the stall, it can be hidden until the user decides to (maybe) click into the specific stall, then the reviews for that stall only will pop up.

Just a suggestion after playing around the app.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Samsation/ped#6

**Comment by Hikoya** [comment]
Thank you for the suggestion. We will take into consideration after v1.4, however for now, this will be the intended functionality for FoodWhere.
